name: Update Progress
on:
  schedule:
    - cron: '0 0 * * *'  # Запуск каждый день в полночь

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install matplotlib
      - name: Generate Progress Chart
        run: python scripts/update_progress.py
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add progress.md progress.svg
          git commit -m "Обновление прогресса"
          git push